/* DO NOT EDIT THIS FILE - it is machine generated */ // generated with javah
#include <jni.h>
/* Header for class ru_woesss_j2me_micro3d_v3_Program */

#ifndef _Included_ru_woesss_j2me_micro3d_v3_Program
#define _Included_ru_woesss_j2me_micro3d_v3_Program
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_ru_woesss_j2me_micro3d_Program__1loadShader
        (JNIEnv *env, jclass, jboolean fragment, jstring sourceStr);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glUseProgram
        (JNIEnv *env, jclass, jint program);
        
JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glDeleteProgram
        (JNIEnv *env, jclass, jint program);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glReleaseShaderCompiler
        (JNIEnv *env, jclass);

JNIEXPORT jint JNICALL Java_ru_woesss_j2me_micro3d_Program__1glGetShaderLocation
        (JNIEnv *env, jclass, jint pid, jboolean uniform, jstring nameStr);

JNIEXPORT jint JNICALL Java_ru_woesss_j2me_micro3d_Program__1doCreateProgram
        (JNIEnv *env, jclass, jint vertexId, jint fragmentId);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glUniform1f
    (JNIEnv *env, jclass, jint id, jfloat a);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glUniform1i
    (JNIEnv *env, jclass, jint id, jint a);
    
JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glUniform2f
    (JNIEnv *env, jclass, jint id, jfloat a, jfloat b);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glUniform3f
    (JNIEnv *env, jclass, jint id, jfloat a, jfloat b, jfloat c);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1glVertexAttrib3f
    (JNIEnv *env, jclass, jint id, jfloat a, jfloat b, jfloat c);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1bindMatrices(JNIEnv* env, jobject obj, jint uMatrix, jint uNormalMatrix, jfloatArray mvp, jfloatArray mv);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1bindTexture2D(JNIEnv* env, jobject obj, jint no, jint tid);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_Program__1unbindTexture2D(JNIEnv* env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif //_Included_ru_woesss_j2me_micro3d_v3_Program
