/* DO NOT EDIT THIS FILE - it is machine generated */ // generated with javah
#include <jni.h>
/* Header for class ru_woesss_j2me_micro3d_v3_TextureImpl */

#ifndef _Included_ru_woesss_j2me_micro3d_v3_TextureImpl
#define _Included_ru_woesss_j2me_micro3d_v3_TextureImpl
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_ru_woesss_j2me_micro3d_TextureImpl__1glIsTexture
        (JNIEnv *env, jclass, jint id);

JNIEXPORT jint JNICALL Java_ru_woesss_j2me_micro3d_TextureImpl__1glGenTextureId
        (JNIEnv *env, jclass, jint biggerThan);

JNIEXPORT void JNICALL Java_ru_woesss_j2me_micro3d_TextureImpl__1loadToGl
        (JNIEnv *env, jclass, jint textId, jint widdth, jint height, jboolean filter, jobject data);

#ifdef __cplusplus
}
#endif
#endif //_Included_ru_woesss_j2me_micro3d_v3_TextureImpl
